joint_limits:
  left_e0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  left_e1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  left_s0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  left_s1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  left_w0:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: false
  left_w1:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: false
  left_w2:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: false
  right_e0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  right_e1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  right_s0:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  right_s1:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
  right_w0:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: false
  right_w1:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: false
  right_w2:
    has_velocity_limits: true
    max_velocity: 4.0
    has_acceleration_limits: false
